.TH "src/main.c" 3 "Fri Nov 23 2018" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- Program for the main\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include 'include/shell\&.h'\fP
.br
\fC#include 'lexer/include/lexer_struct\&.h'\fP
.br
\fC#include 'lexer/include/my_tree\&.h'\fP
.br
\fC#include 'lexer/include/rule\&.h'\fP
.br
\fC#include 'print_ast/include/print_ast\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd_token\fP (struct Token **token, char *str)"
.br
.ti -1c
.RI "struct Token * \fBparse_path\fP (struct Token *token, char **argv, long argc, struct PS *ps)"
.br
.ti -1c
.RI "void \fBprint_t\fP (struct Token *t)"
.br
.RI "\fIPrinting AST function\&. \fP"
.ti -1c
.RI "struct Token * \fBlexer\fP (struct Token *t)"
.br
.ti -1c
.RI "void \fBDestroyToken\fP (struct Token *t)"
.br
.ti -1c
.RI "struct PS * \fBinit_ps\fP (void)"
.br
.ti -1c
.RI "struct Token * \fBcarving\fP (long argc, char **argv)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Program for the main\&. 


.IP "\(bu" 2
\fBVersion:\fP
.RS 4
0\&.5 
.RE
.PP
\fBDate:\fP
.RS 4
30 novembre 2018
.RE
.PP
File with the main 
.PP

.SH "Function Documentation"
.PP 
.SS "void print_t (struct Token * t)"

.PP
Printing AST function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP Adress of the pointer structure to be print\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
No return\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
